// Test error_message variable in catch blocks
display "Testing error_message variable..."

try:
    display "About to cause an error"
    store result as 10 divided by 0
    display "This should not execute"
catch:
    display "Caught error: " with error
end try

display "Test completed"
